const model = require('./model')
const runtime = require('./runtime')
const uploadFlow = require('./upload-flow')
const accountReview = require('./account-review')
const transactionReview = require('./transaction-review')
const postingFlow = require('./posting-flow')

const initialData = {
    restoreUpdateId: '',
    abandoningRestore: false,
    phase: 'idle',
    maxFiles: uploadFlow.MAX_FILES,
    currentStep: 1,
    reviewPage: { index: 0, pages: 1, count: 0 },
    unlockedStep: 1,
    busy: false,
    files: [],
    bankMappingSheet: null,
    fileAttentionSheet: null,
    historicalCandidates: [],
    historicalPage: null,
    historicalSelection: '',
    historicalLoading: false,
    historicalError: '',
    uploadSummary: { total: 0, queued: 0, ready: 0, failed: 0, mapping: 0, duplicate: 0, attention: 0 },
    pendingInstallments: false,
    update: null,
    sources: [],
    events: [],
    issues: [],
    accountIssues: [],
    accountMappings: [],
    draftSync: { pending: 0, syncing: false, error: '', conflicts: 0 },
    accountStepSummary: { total: 0, ready: 0, confirmed: 0, invalid: 0, create: 0, inline: 0, transfer: 0, open: 0, dirty: 0, pending: 0 },
    accountStepBusy: false,
    accountStepError: '',
    accountStepProgressText: '',
    reviewIssues: [],
    reviewGroups: [],
    verificationIssues: [],
    categoryIssues: [],
    categoryCards: [],
    categoryQuery: '',
    categoryEventCount: 0,
    categorizedEvents: [],
    categorizedEventCount: 0,
    recordSummary: { totalCount: 0, activeCount: 0, excludedCount: 0, duplicateCount: 0 },
    reviewedEvents: [],
    categoryWaitingEvents: [],
    noCategoryEvents: [],
    activeCategoryStatus: 'pending',
    categoryStatusTabs: model.organizerRecordState([], [], []).categoryStatusTabs,
    activeReviewTab: 'review',
    issueSourceExpanded: false,
    issueFieldsReason: '',
    paymentValidationHint: '',
    duplicateReviewCandidates: [],
    duplicateReviewLoading: false,
    duplicateReviewLoaded: false,
    duplicateReviewError: '',

    reviewStatusTabs: [
      { value: 'pending', label: '待核对', count: 0 },
      { value: 'completed', label: '已核对', count: 0 },
      { value: 'excluded', label: '已排除', count: 0 },
      { value: 'duplicate', label: '重复', count: 0 }
    ],
    activeReviewStatus: 'pending',
    excludedReviewGroups: [],
    duplicateReviewEvents: [],
    openIssueCount: 0,
    coverage: {
      dataRows: 0,
      recognizedRows: 0,
      unrecognizedRows: 0,
      selectedEvents: 0,
      readySelectedEvents: 0,
      pendingSelectedEvents: 0,
      excludedEvents: 0,
      statementFullyRecognized: false,
      selectedEventsReadyToPost: false
    },
    accounts: [],
    accountDrafts: [],
    accountMappingDrafts: [],
    accountChoices: [{ accountId: '', name: '新建账户' }],
    counterpartyAccountChoices: [{ accountId: '', name: '请选择转入账户', isPlaceholder: true }],
    accountChoiceSheet: null,
    accountChoiceQuery: '',
    accountChoiceResults: [],
    choiceLoading: false,
    accountTypeOptions: accountReview.ACCOUNT_TYPE_OPTIONS,
    categories: [],
    issueCategories: [],
    posting: null,
    fundsFlowGroups: [],
    finalDetailSheet: null,
    finalDetailScrollTop: 0,
    finalDetailParent: null,
    finalSummary: {
      expenseCount: 0, incomeCount: 0, refundCount: 0,
      expenseText: '¥0.00', incomeText: '¥0.00', refundText: '¥0.00', transferCount: 0,
      categoryCoverageText: '无需分类', categoryComplete: true, newAccountCount: 0, affectedAccountCount: 0
    },
    errorMessage: '',
    paymentRows: [], paymentNatureOptions: ['请选择交易性质', '本次消费支出', '偿还既有欠款'], paymentNatureIndex: 0,
    paymentTargetIndex: 0, paymentEvidenceNote: '', paymentCanSave: false, paymentDifferenceText: '',
    bankSuggestion: null,
    bankBatchCandidates: [],
    bankBatchRecords: [],
    bankBatchExpanded: false,
    bankBatchLoading: false,
    bankBatchSelectedCount: 0,
    currentIssue: null,
    issueFieldsCanSave: false,
    currentMembers: [],
    issueEvents: [],
    issueVisibleEvents: [],
    issueEvidenceLoading: false,
    issueEvidenceHasMore: false,
    issueEvidenceTotal: 0,
    issueRelations: [],
    repaymentAllocationChoices: [],
    repaymentAccountOptions: [],
    repaymentAdditionalOptions: [],
    repaymentAdditionalIndex: 0,
    repaymentAllocationStatusText: '',
    repaymentAllocationCanSave: false,
    evidenceSheet: null,
    accountRecordsSheet: null,
    issueDraft: {
      accountIndex: 0,
      counterpartyAccountIndex: 0,
      categoryIndex: 0,
      natureIndex: 0,
      primaryEventId: '',
      targetEventId: '',
      newAccountName: '',
      accountTypeIndex: 2
    },
    natureOptions: transactionReview.NATURE_OPTIONS,
    themeClass: '',
    themeStyle: ''
  }

// 每个页面处理者只有一个明确归属；不依赖对象覆盖顺序。
Page({
  data: initialData,
  businessData: runtime.businessData,
  mappingState: accountReview.mappingState,
  refreshAccountMappings: accountReview.refreshAccountMappings,
  onLoad: runtime.onLoad,
  onHide: runtime.onHide,
  onUnload: runtime.onUnload,
  onShow() { return runtime.onShow.call(this, initialData) },
  chooseFiles: uploadFlow.chooseFiles,
  openFilePicker: uploadFlow.openFilePicker,
  readLocalFile: uploadFlow.readLocalFile,
  isDuplicateLocalFile: uploadFlow.isDuplicateLocalFile,
  startUpload: uploadFlow.startUpload,
  uploadAndParseFile: uploadFlow.uploadAndParseFile,
  uploadObject: uploadFlow.uploadObject,
  setFileProgress: uploadFlow.setFileProgress,
  clearFileProgressThrottle: uploadFlow.clearFileProgressThrottle,
  parsePreparedFile: uploadFlow.parsePreparedFile,
  openBankMapping: uploadFlow.openBankMapping,
  showFileFailure: uploadFlow.showFileFailure,
  openFileAttention: uploadFlow.openFileAttention,
  tapFileRow: uploadFlow.tapFileRow,
  closeFileAttention: uploadFlow.closeFileAttention,
  retryFileAttention: uploadFlow.retryFileAttention,
  closeBankMapping: uploadFlow.closeBankMapping,
  changeBankMapping: uploadFlow.changeBankMapping,
  toggleBankColumns: uploadFlow.toggleBankColumns,
  inputBankHeader: uploadFlow.inputBankHeader,
  refreshBankPreview: uploadFlow.refreshBankPreview,
  confirmBankMapping: uploadFlow.confirmBankMapping,
  setFileState: uploadFlow.setFileState,
  syncUploadSummary: uploadFlow.syncUploadSummary,
  retryFile: uploadFlow.retryFile,
  removeFile: uploadFlow.removeFile,
  createFinanceUpdate: runtime.createFinanceUpdate,
  refreshAccountGroups: runtime.refreshAccountGroups,
  loadUpdate: runtime.loadUpdate,
  abandonRestoringUpdate: runtime.abandonRestoringUpdate,
  toggleIssueSource: transactionReview.toggleIssueSource,
  switchReviewTab: transactionReview.switchReviewTab,
  switchCategoryStatus: transactionReview.switchCategoryStatus,
  searchCategoryIssues: transactionReview.searchCategoryIssues,
  reviewBeforeCategory: transactionReview.reviewBeforeCategory,
  viewTransactions: postingFlow.viewTransactions,
  viewStatistics: postingFlow.viewStatistics,
  completeCategories: postingFlow.completeCategories,
  correctBalances: postingFlow.correctBalances,
  openInstallmentSources: postingFlow.openInstallmentSources,
  switchReviewStatus: transactionReview.switchReviewStatus,
  toggleExcludedGroup: transactionReview.toggleExcludedGroup,
  buildAccountMappingState: accountReview.buildAccountMappingState,
  openAccountChoice: accountReview.openAccountChoice,
  closeAccountChoice: accountReview.closeAccountChoice,
  selectAccountChoice: accountReview.selectAccountChoice,
  preventTouchMove: runtime.preventTouchMove,
  closeAccountRecords: accountReview.closeAccountRecords,
  closeReviewSheet: transactionReview.closeReviewSheet,
  bindAccountDraftName: accountReview.bindAccountDraftName,
  scheduleAccountDraftSync: accountReview.scheduleAccountDraftSync,
  flushAccountDraftSync: accountReview.flushAccountDraftSync,
  changeAccountDraftType: accountReview.changeAccountDraftType,
  completeAccountMapping: accountReview.completeAccountMapping,
  persistAccountDrafts: accountReview.persistAccountDrafts,
  accountMappingDecision: accountReview.accountMappingDecision,
  retryDraftSync: runtime.retryDraftSync,
  finishDraftStep: runtime.finishDraftStep,
  goToStep: runtime.goToStep,
  openIssue: transactionReview.openIssue,
  closeIssue: transactionReview.closeIssue,
  backFinalDetail: postingFlow.backFinalDetail,
  prepareFinalDetail: postingFlow.prepareFinalDetail,
  closeFinalDetail: postingFlow.closeFinalDetail,
  closeEvidence: transactionReview.closeEvidence,
  beginInputEditing: runtime.beginInputEditing,
  finishInputEditing: runtime.finishInputEditing,
  refreshIssueFieldsDraft: transactionReview.refreshIssueFieldsDraft,
  changeRepaymentOwner: transactionReview.changeRepaymentOwner,
  changeRepaymentOtherTreatment: transactionReview.changeRepaymentOtherTreatment,
  changeIssueAccount: transactionReview.changeIssueAccount,
  refreshPaymentDraft: transactionReview.refreshPaymentDraft,
  changePaymentRow: transactionReview.changePaymentRow,
  fillPaymentAmount: transactionReview.fillPaymentAmount,
  changePaymentNature: transactionReview.changePaymentNature,
  changePaymentTarget: transactionReview.changePaymentTarget,
  changePaymentNote: transactionReview.changePaymentNote,
  selectBankSuggestion: transactionReview.selectBankSuggestion,
  toggleBankBatch: transactionReview.toggleBankBatch,
  resolveBankBatch: transactionReview.resolveBankBatch,
  refreshRepaymentChoices: transactionReview.refreshRepaymentChoices,
  addRepaymentAccount: transactionReview.addRepaymentAccount,
  removeRepaymentAccount: transactionReview.removeRepaymentAccount,
  changeRepaymentAccountName: transactionReview.changeRepaymentAccountName,
  changeRepaymentAllocation: transactionReview.changeRepaymentAllocation,
  fillRepaymentAllocation: transactionReview.fillRepaymentAllocation,
  changeCounterpartyAccount: transactionReview.changeCounterpartyAccount,
  changeDraftAccountName: transactionReview.changeDraftAccountName,
  changeDraftAccountType: transactionReview.changeDraftAccountType,
  changeIssueCategory: transactionReview.changeIssueCategory,
  changeIssueNature: transactionReview.changeIssueNature,
  selectPrimaryEvent: transactionReview.selectPrimaryEvent,
  selectTargetRelation: transactionReview.selectTargetRelation,
  resolveWithFields: transactionReview.resolveWithFields,
  confirmDistinct: transactionReview.confirmDistinct,
  confirmSame: transactionReview.confirmSame,
  linkRefund: transactionReview.linkRefund,
  markRefundPending: transactionReview.markRefundPending,
  confirmInstallment: transactionReview.confirmInstallment,
  reviewDraftEntry: transactionReview.reviewDraftEntry,
  restoreReviewDraft: transactionReview.restoreReviewDraft,
  recheckDraftConflicts: transactionReview.recheckDraftConflicts,
  resolveIssue: transactionReview.resolveIssue,
  abandonUpdate: postingFlow.abandonUpdate,
  performAbandonUpdate: postingFlow.performAbandonUpdate,
  openImportHistory: postingFlow.openImportHistory,
  startAnother: runtime.startAnother,
  applyPendingBackgroundView: runtime.applyPendingBackgroundView,
  cancelPagedReads: runtime.cancelPagedReads,
  request: runtime.request,
  loadDirectories: accountReview.loadDirectories,
  bindAccountChoiceSearch: accountReview.bindAccountChoiceSearch,
  changeChoiceKind: accountReview.changeChoiceKind,
  changeChoicePage: accountReview.changeChoicePage,
  openDirectory: accountReview.openDirectory,
  searchDirectory: accountReview.searchDirectory,
  changeDirectoryKind: accountReview.changeDirectoryKind,
  changeDirectoryPage: accountReview.changeDirectoryPage,
  selectDirectory: accountReview.selectDirectory,
  closeDirectory: accountReview.closeDirectory,
  openAccountRecords: accountReview.openAccountRecords,
  changeAccountMembers: accountReview.changeAccountMembers,
  readIssue: transactionReview.readIssue,
  excludeIssueEvents: transactionReview.excludeIssueEvents,
  selectPrimaryMember: transactionReview.selectPrimaryMember,
  expandBankBatch: transactionReview.expandBankBatch,
  changeHistoricalPage: transactionReview.changeHistoricalPage,
  selectHistoricalTransaction: transactionReview.selectHistoricalTransaction,
  linkHistoricalTransaction: transactionReview.linkHistoricalTransaction,
  refreshHistoricalReview: transactionReview.refreshHistoricalReview,
  changeIssueMembers: transactionReview.changeIssueMembers,
  changeIssueRelations: transactionReview.changeIssueRelations,
  closeInlineEvidence: transactionReview.closeInlineEvidence,
  loadInlineEvidence: transactionReview.loadInlineEvidence,
  changeInlineSource: transactionReview.changeInlineSource,
  retryIssueRecordEvidence: transactionReview.retryIssueRecordEvidence,
  retryAccountRecordEvidence: transactionReview.retryAccountRecordEvidence,
  editLoanRepayment: transactionReview.editLoanRepayment,
  openEvidence: transactionReview.openEvidence,
  changeEvidencePage: transactionReview.changeEvidencePage,
  openEvidencePart: transactionReview.openEvidencePart,
  changeEvidencePart: transactionReview.changeEvidencePart,
  applyUpdateView: runtime.applyUpdateView,
  stepPatch: runtime.stepPatch,
  setStep: runtime.setStep,
  renderReview: runtime.renderReview,
  loadDuplicateRecords: runtime.loadDuplicateRecords,
  loadActivePage: runtime.loadActivePage,
  changeReviewPage: runtime.changeReviewPage,
  retryPagedView: runtime.retryPagedView,
  openFinalDetail: postingFlow.openFinalDetail,
  changeFinalPage: postingFlow.changeFinalPage,
  openFinalAccount: postingFlow.openFinalAccount,
  postUpdate: postingFlow.postUpdate
})
