const { test } = require('node:test')
const assert = require('node:assert/strict')
const { randomUUID } = require('node:crypto')
const { readFileSync } = require('node:fs')
const path = require('node:path')
const { splitSqlStatements } = require('../migrations/runner')
const { localServices, call, prepareSyntheticUpdate } = require('./helpers/local-services')
const { DEFAULT_CATEGORIES } = require('../cloudfunctions/catledger-api/src/default-categories')
const hasDatabase = ['HOST', 'USER', 'PASSWORD', 'NAME'].every(key => process.env['CATLEDGER_TEST_DB_' + key])
test('两级分类隔离数据库：迁移、旧账、目录、同级约束、重放、退款、筛选、停用及导入', { skip: !hasDatabase, timeout: 60000 }, async t => {
  const db = await require('../scripts/isolated-mysql').isolatedMysql()
  try {
    const grants = require('../scripts/runtime-role-grants')
    const apiPool = await db.role('api', grants.api), importPool = await db.role('import', grants.importer)
    const services = localServices({ apiPool, importPool }), api = (action,data) => call(services.api,action,data)
    const other = localServices({ apiPool, importPool, subject: 'synthetic-category-other' })
    const identity = await api('bootstrap'), otherIdentity = await call(other.api, 'bootstrap')
    const parent = identity.categories.find(row => row.systemKey === 'food')
    const children = identity.categories.filter(row => row.parentId === parent.id)
    const revision = async () => String((await db.owner.execute('SELECT data_revision AS r FROM catledger_users WHERE uid=?',[identity.uid]))[0][0].r)
    const create = (name,parentId=null,kind='expense',requestId=randomUUID()) => api('categories.create',{requestId,name,parentId,kind})
    await t.test('旧用户升级保留 ID、改名、停用和旧交易，自定义同名分类不接管', async () => {
      const { createUserRepository } = require('../cloudfunctions/catledger-api/src/user-repository')
      const { hashWechatSubject } = require('../cloudfunctions/catledger-api/src/handler')
      const { ROOT_CATEGORIES } = require('../cloudfunctions/catledger-api/src/default-categories')
      const subject = 'synthetic-legacy-categories', legacy = localServices({ apiPool, importPool, subject })
      const old = await createUserRepository({ getPool: () => apiPool, defaultCategories: ROOT_CATEGORIES.filter(row => !['finance','communication'].includes(row.systemKey)) })
        .bootstrap({ provider: 'wechat-mini', subjectHash: hashWechatSubject(subject) })
      const oldFood = old.categories.find(row => row.systemKey === 'food'), oldMedical = old.categories.find(row => row.systemKey === 'medical')
      const legacyApi = (action,data) => call(legacy.api,action,data)
      await legacyApi('categories.update',{requestId:randomUUID(),categoryId:oldFood.id,version:1,name:'原有分类已改名'})
      await legacyApi('categories.archive',{requestId:randomUUID(),categoryId:oldMedical.id,version:1})
      const custom = await legacyApi('categories.create',{requestId:randomUUID(),kind:'expense',name:'通讯'})
      const a = await legacyApi('accounts.create',{requestId:randomUUID(),name:'旧账合成账户',type:'wallet',openingDisplayBalanceMinor:'1000',occurredLocalAt:'2026-08-01T00:00:00',timezoneOffsetMinutes:-480})
      const tx = await legacyApi('transactions.create',{requestId:randomUUID(),type:'expense',sourceAccountId:a.accountId,categoryId:oldFood.id,amountMinor:'100',occurredLocalAt:'2026-08-02T00:00:00',timezoneOffsetMinutes:-480})
      const before = (await db.owner.execute('SELECT * FROM catledger_transactions WHERE uid=?',[old.uid]))[0]
      const upgraded = await legacyApi('bootstrap'), categories = (await legacyApi('categories.list')).categories
      assert.equal(upgraded.categories.find(row=>row.systemKey==='food').id,oldFood.id)
      assert.equal(categories.find(row=>row.id===oldFood.id).name,'原有分类已改名')
      assert.equal(categories.find(row=>row.id===oldMedical.id).archived,true)
      assert.ok(!categories.some(row=>row.parentId===oldMedical.id))
      assert.equal(categories.find(row=>row.id===custom.id).systemKey,null)
      assert.ok(!categories.some(row=>row.systemKey==='communication'))
      assert.deepEqual((await db.owner.execute('SELECT * FROM catledger_transactions WHERE uid=?',[old.uid]))[0],before)
      assert.equal((await legacyApi('transactions.list',{month:'2026-08'})).transactions[0].transactionId,tx.transactionId)
      const rev = (await db.owner.execute('SELECT data_revision AS r FROM catledger_users WHERE uid=?',[old.uid]))[0][0].r
      await legacyApi('bootstrap')
      assert.equal((await db.owner.execute('SELECT data_revision AS r FROM catledger_users WHERE uid=?',[old.uid]))[0][0].r,rev)
    })
    await t.test('初始化只补预设，重复登录不推进版本或改名；重跑迁移不改已有行',async()=>{
      assert.equal(identity.categories.length,DEFAULT_CATEGORIES.length); assert.equal(children.length,3)
      const before = await revision(), initial = JSON.stringify(identity.categories)
      assert.equal(JSON.stringify((await api('bootstrap')).categories),initial); assert.equal(await revision(),before)
      const connection=await db.owner.getConnection()
      try { for(const statement of splitSqlStatements(readFileSync(path.join(__dirname,'../migrations/0022_category_hierarchy.sql'),'utf8'))) await connection.query(statement) } finally { connection.release() }
      assert.equal(JSON.stringify((await api('bootstrap')).categories),initial); assert.equal(await revision(),before)
      const updated=await api('categories.update',{requestId:randomUUID(),categoryId:parent.id,version:1,name:'合成餐饮改名'})
      assert.equal(updated.systemKey,'food');assert.equal((await api('bootstrap')).categories.find(row=>row.id===parent.id).name,'合成餐饮改名')
      parent.version=updated.version
    })
    await t.test('同级唯一且跨级可同名，跨用户/类型/第三级与移动父级均拒绝',async()=>{
      const custom=await create('合成自定义'), child=await create('合成自定义',custom.id)
      await assert.rejects(create('合成自定义',custom.id),{publicCode:'CONFLICT'})
      await assert.rejects(create('第三级',child.id),{publicCode:'VALIDATION_ERROR'})
      await assert.rejects(create('类型错误',custom.id,'income'),{publicCode:'VALIDATION_ERROR'})
      await assert.rejects(create('跨用户',otherIdentity.categories[0].id),{publicCode:'NOT_FOUND'})
      await assert.rejects(api('categories.update',{requestId:randomUUID(),categoryId:custom.id,version:1,name:'挪动',parentId:child.id}),{publicCode:'VALIDATION_ERROR'})
      await assert.rejects(db.owner.execute('UPDATE catledger_categories SET parent_id=? WHERE uid=? AND category_id=?',[otherIdentity.categories[0].id,identity.uid,child.id]),{code:'ER_NO_REFERENCED_ROW_2'})
      const id=randomUUID(), rev=await revision()
      const [a,b]=await Promise.all([create('合成重放',null,'expense',id),create('合成重放',null,'expense',id)])
      assert.deepEqual(a,b);assert.equal(BigInt(await revision()),BigInt(rev)+1n)
      const results=await Promise.allSettled([create('合成竞争',custom.id),create('合成竞争',custom.id)])
      assert.equal(results.filter(r=>r.status==='fulfilled').length,1)
    })
    const account=await api('accounts.create',{requestId:randomUUID(),name:'合成层级账户',type:'wallet',openingDisplayBalanceMinor:'10000',occurredLocalAt:'2026-09-01T08:00:00',timezoneOffsetMinutes:-480})
    const expense = (categoryId,amountMinor) => api('transactions.create',{requestId:randomUUID(),type:'expense',sourceAccountId:account.accountId,categoryId,amountMinor,occurredLocalAt:'2026-09-02T10:00:00',timezoneOffsetMinutes:-480})
    const rootTx=await expense(parent.id,'100'), childTx=await expense(children[0].id,'300')
    await api('transactions.create',{requestId:randomUUID(),type:'refund',destinationAccountId:account.accountId,originalTransactionId:childTx.transactionId,amountMinor:'80',occurredLocalAt:'2026-09-03T10:00:00',timezoneOffsetMinutes:-480})
    await t.test('一级直接记账与二级退款汇总一次，父级分页涵盖子级且子级不串联',async()=>{
      const stats=await api('statistics.get',{month:'2026-09'}), group=stats.expenseCategories.find(row=>row.categoryId===parent.id)
      assert.equal(stats.summary.expenseMinor,'320');assert.equal(group.amountMinor,'320')
      assert.equal(group.children.find(row=>row.direct).amountMinor,'100');assert.equal(group.children.find(row=>!row.direct).amountMinor,'220')
      const ids=[];let cursor=null
      do { const page=await api('transactions.list',{month:'2026-09',categoryId:parent.id,pageSize:1,...(cursor?{cursor}:{})});ids.push(...page.transactions.map(row=>row.transactionId));cursor=page.nextCursor } while(cursor)
      assert.equal(ids.length,3);assert.equal(new Set(ids).size,3);assert.ok(ids.includes(rootTx.transactionId))
      const page=await api('transactions.list',{month:'2026-09',categoryId:children[0].id})
      assert.equal(page.transactions.length,2);assert.ok(page.transactions.every(row=>row.category.parentId===parent.id))
      assert.equal((await api('accounts.list')).accounts[0].bookBalanceMinor,'9680')
    })
    await t.test('同级排序乐观版本，失效或混层请求全回滚',async()=>{
      const order=children.slice().reverse().map(row=>({categoryId:row.id,version:1}))
      const result=await api('categories.reorder',{requestId:randomUUID(),kind:'expense',parentId:parent.id,items:order})
      assert.deepEqual(result.categories.map(row=>row.id),order.map(row=>row.categoryId))
      const rev=await revision()
      await assert.rejects(api('categories.reorder',{requestId:randomUUID(),kind:'expense',parentId:parent.id,items:order}),{publicCode:'CONFLICT'})
      assert.equal(await revision(),rev)
    })
    await t.test('父类停用原子停用子类，旧交易与统计保留；恢复逐项操作',async()=>{
      const request={requestId:randomUUID(),categoryId:parent.id,version:parent.version}
      const archived=await api('categories.archive',request)
      assert.equal(archived.categories.length,4);assert.ok(archived.categories.every(row=>row.archived))
      const rev=await revision();assert.deepEqual(await api('categories.archive',request),archived);assert.equal(await revision(),rev)
      await assert.rejects(api('categories.restore',{requestId:randomUUID(),categoryId:children[0].id,version:3}),{publicCode:'CONFLICT'})
      await assert.rejects(expense(children[0].id,'1'))
      assert.equal((await api('statistics.get',{month:'2026-09'})).summary.expenseMinor,'320')
      assert.ok(!(await api('catalog.get')).categories.some(row=>row.parentId===parent.id))
      const restored=await api('categories.restore',{requestId:randomUUID(),categoryId:parent.id,version:archived.version})
      assert.equal(restored.archived,false)
      assert.ok(!(await api('bootstrap')).categories.some(row=>row.parentId===parent.id))
      await api('categories.restore',{requestId:randomUUID(),categoryId:children[0].id,version:3})
      assert.equal((await api('catalog.get')).categories.filter(row=>row.parentId===parent.id).length,1)
    })
    await t.test('导入分页目录返回父名，按大类名称搜索包括子类且隔离用户',async()=>{
      const update=await prepareSyntheticUpdate(services,1,'SYNTHETIC-CATEGORY')
      const page=await call(services.import,'financeUpdates.options',{updateId:update.updateId,kind:'categories',query:'合成餐饮改名'})
      assert.equal(page.items.length,2);assert.equal(page.items.find(row=>row.parentId).parentName,'合成餐饮改名')
      await assert.rejects(call(other.import,'financeUpdates.options',{updateId:update.updateId,kind:'categories'}),{publicCode:'NOT_FOUND'})
    })
  } finally { await db.close() }
})
