const test = require('node:test')
const assert = require('node:assert/strict')
const { randomUUID } = require('node:crypto')
const { chargeLab, prepareBank, postBank } = require('./helpers/loan-charges')
const { realPage } = require('./helpers/real-page')
const tap = (id, index = 0) => ({ currentTarget: { dataset: { id, index } } })

test('真实交易Page明确分配已有信用卡转账，复用费用、期次和原付款', { skip: !process.env.CATLEDGER_TEST_DB_HOST, timeout: 120000 }, async t => {
  const h = await chargeLab()
  try {
    await postBank(h, await prepareBank(h, { period: 1, date: '2026-01-31' }))
    const source = (await h.api('loans.installmentSources')).items[0]
    const loan = await h.create({ sourceItemId: source.itemId })
    const transfer = () => h.api('transactions.create', { requestId: randomUUID(), type: 'transfer', sourceAccountId: h.assetAccountId,
      destinationAccountId: h.accountId, amountMinor: '100000', occurredLocalAt: '2026-01-31T12:00:00', timezoneOffsetMinutes: -480 })
    const txn = await transfer(), independent = await transfer(), ui = realPage(h)
    const context = await h.api('loans.transaction', { transactionId: txn.transactionId })
    assert.equal(context.state, 'allocatable')
    assert.equal(context.payment, null)
    assert.deepEqual(context.allocations, [])
    ui.app.globalData.editingTransaction = context.transaction
    const editor = ui.page('transaction-editor')
    editor.onLoad({ mode: 'view' }); await editor.prepareForm(); await editor.loadLoanContext()
    editor.openLoanLink()
    assert.equal(ui.navigation.at(-1), '/pages/loan-link/index?transactionId=' + txn.transactionId)
    const link = ui.page('loan-link'); link.onLoad({ transactionId: txn.transactionId }); await link.firstPage()
    link.selectLoan(tap(loan.loanId))
    assert.equal(ui.navigation.at(-1), '/pages/loan-payment/index?loanId=' + loan.loanId + '&sourceTransactionId=' + txn.transactionId)
    const page = ui.page('loan-payment'); page.onLoad({ loanId: loan.loanId, sourceTransactionId: txn.transactionId }); await page.load()
    page.periodInput({ currentTarget: { dataset: { index: 0 } }, detail: { value: '1' } }); await page.selectAllocationPeriod(tap(loan.loanId))
    assert.equal(page.data.allocations[0].principalYuan, '500.00')
    assert.equal(page.data.allocations[0].interestIndex, 1)
    assert.equal(page.data.allocations[0].chargeChoices.find(c => c.selected).paidYuan, '20.00')
    page.input({ currentTarget: { dataset: { field: 'unallocatedYuan' } }, detail: { value: '480' } })
    page.confirm({ detail: { value: ['confirmed'] } })
    const before = (await h.api('accounts.list')).accounts
    await Promise.all([page.save(), page.save()])
    assert.equal(page.data.errorMessage, '')
    assert.equal(page.data.payment.mode, 'associate')
    assert.equal(page.data.unallocatedText, '¥480.00')
    assert.equal(page.data.transactions.length, 1)
    assert.equal(page.data.transactions[0].transactionId, txn.transactionId)
    assert.deepEqual((await h.api('accounts.list')).accounts, before)
    assert.equal((await h.state(loan)).items[0].transactionId, source.transactionId)
    const request = ui.calls.find(c => c.action === 'loans.record').data
    const receipt = await h.api('loans.record', request)
    assert.equal(receipt.paymentId, page.data.payment.paymentId)
    await assert.rejects(h.api('loans.record', { ...request, requestId: randomUUID() }), { publicCode: 'CONFLICT' })
    assert.equal((await h.api('loans.transaction', { transactionId: independent.transactionId })).state, 'allocatable')
    await page.beginEdit(false)
    assert.equal(page.data.modeIndex, 1)
    page.editAllocation({ currentTarget: { dataset: { index: 0, field: 'principalYuan' } }, detail: { value: '490' } })
    page.input({ currentTarget: { dataset: { field: 'unallocatedYuan' } }, detail: { value: '490' } })
    page.confirm({ detail: { value: ['confirmed'] } }); await page.save()
    assert.equal(page.data.errorMessage, '')
    assert.equal(page.data.transactions[0].transactionId, txn.transactionId)
    assert.equal(page.data.unallocatedText, '¥490.00')
    assert.deepEqual((await h.api('accounts.list')).accounts, before)
    const corrected = page.data.payment
    await page.confirmReverse()
    assert.equal(page.data.errorMessage, '')
    assert.equal((await h.api('loans.transaction', { transactionId: txn.transactionId })).state, 'allocatable')
    assert.deepEqual((await h.api('accounts.list')).accounts, before)
    assert.equal((await h.api('loans.payment', { paymentId: corrected.paymentId })).payment.status, 'reversed')
    await t.test('同一原转账在真实Page分配给两笔分期，并发保存只占用一次', async () => {
      const first=await h.create({repaymentMinor:'50000'}),second=await h.create({repaymentMinor:'50000'})
      const multi=realPage(h),p=multi.page('loan-payment');p.onLoad({loanId:first.loanId,sourceTransactionId:independent.transactionId});await p.load()
      p.periodInput({currentTarget:{dataset:{index:0}},detail:{value:'1'}});await p.selectAllocationPeriod(tap(first.loanId))
      await p.moreLoans();await p.addLoan(tap(second.loanId))
      p.periodInput({currentTarget:{dataset:{index:1}},detail:{value:'1'}});await p.selectAllocationPeriod(tap(second.loanId,1))
      p.editAllocation({currentTarget:{dataset:{index:1,field:'principalYuan'}},detail:{value:'400'}})
      p.input({currentTarget:{dataset:{field:'unallocatedYuan'}},detail:{value:'100'}})
      p.confirm({detail:{value:['confirmed']}})
      const payload=multi.load('pages/loan-payment/model').payload(p.data),before=(await h.api('accounts.list')).accounts
      const results=await Promise.allSettled([h.api('loans.record',{...payload,requestId:randomUUID()}),h.api('loans.record',{...payload,requestId:randomUUID()})])
      assert.equal(results.filter(r=>r.status==='fulfilled').length,1)
      const paid=results.find(r=>r.status==='fulfilled').value
      assert.equal((await h.api('loans.payment',{paymentId:paid.paymentId})).allocations.length,2)
      assert.equal((await h.api('loans.get',{loanId:first.loanId})).loan.remainingPrincipalMinor,'550000')
      assert.equal((await h.api('loans.get',{loanId:second.loanId})).loan.remainingPrincipalMinor,'560000')
      assert.deepEqual((await h.api('accounts.list')).accounts,before)
      await assert.rejects(h.api('loans.source',{transactionIds:[independent.transactionId]}),{publicCode:'LOAN_TRANSACTION_LOCKED'})
    })
    await t.test('历史已还后由真实Page补凭证和更正，基准不重复冲减', async () => {
      const history=await h.create(),transaction=await transfer()
      await h.api('loans.confirmInstallments',{requestId:randomUUID(),loanId:history.loanId,version:1,repayments:[{periodNumber:1,paid:true}]})
      const ui=realPage(h),p=ui.page('loan-payment');p.onLoad({loanId:history.loanId,sourceTransactionId:transaction.transactionId});await p.load()
      p.periodInput({currentTarget:{dataset:{index:0}},detail:{value:'1'}});await p.selectAllocationPeriod(tap(history.loanId))
      assert.equal(p.data.errorMessage,'')
      p.input({currentTarget:{dataset:{field:'unallocatedYuan'}},detail:{value:'480'}});p.confirm({detail:{value:['confirmed']}});await p.save()
      assert.equal(p.data.errorMessage,'')
      assert.equal((await h.api('loans.get',{loanId:history.loanId})).loan.remainingPrincipalMinor,'550000')
      await p.beginEdit(false);p.confirm({detail:{value:['confirmed']}});await p.save()
      assert.equal(p.data.errorMessage,'')
      assert.equal((await h.api('loans.get',{loanId:history.loanId})).loan.remainingPrincipalMinor,'550000')
      const charge=(await h.state(history)).items[0]
      assert.equal(charge.settledMinor,'2000');assert.equal(charge.historicalCoveredMinor,'0')
    })
    await t.test('来源过期、删除、跨用户和中途失败均不能留下关联', async () => {
      const fresh=await h.create({repaymentMinor:'50000'}),transaction=await transfer()
      const source=(await h.api('loans.source',{transactionIds:[transaction.transactionId]})).source
      const input={requestId:randomUUID(),mode:'associate',source,kind:'repayment',assetAccountId:h.assetAccountId,totalMinor:'100000',unallocatedMinor:'50000',occurredLocalAt:'2026-01-31T12:00:00',timezoneOffsetMinutes:-480,confirmed:true,
        allocations:[{loanId:fresh.loanId,version:1,period:{periodNumber:1,version:1},principalMinor:'50000',interestMinor:'0',feeMinor:'0',interestTreatment:'expense',feeTreatment:'expense'}]}
      await h.owner.query("CREATE TRIGGER fail_credit_link BEFORE INSERT ON catledger_loan_payment_transactions FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='synthetic credit rollback'")
      try{await assert.rejects(h.api('loans.record',input),{publicCode:'INTERNAL_ERROR'})}finally{await h.owner.query('DROP TRIGGER fail_credit_link')}
      assert.equal((await h.api('loans.transaction',{transactionId:transaction.transactionId})).state,'allocatable')
      assert.equal((await h.api('loans.get',{loanId:fresh.loanId})).loan.version,1)
      const {localServices,call}=require('./helpers/local-services'),other=localServices({apiPool:h.apiPool,importPool:h.importPool,subject:'synthetic-other-credit'})
      await call(other.api,'bootstrap')
      await assert.rejects(call(other.api,'loans.transaction',{transactionId:transaction.transactionId}),{publicCode:'NOT_FOUND'})
      await h.api('transactions.update',{requestId:randomUUID(),transactionId:transaction.transactionId,version:1,type:'transfer',sourceAccountId:h.assetAccountId,destinationAccountId:h.accountId,amountMinor:'100001',occurredLocalAt:'2026-01-31T12:00:00',timezoneOffsetMinutes:-480})
      await assert.rejects(h.api('loans.record',{...input,requestId:randomUUID()}),{publicCode:'CONFLICT'})
      await h.api('transactions.delete',{requestId:randomUUID(),transactionId:transaction.transactionId,version:2})
      await assert.rejects(h.api('loans.transaction',{transactionId:transaction.transactionId}),{publicCode:'NOT_FOUND'})
    })
  } finally { await h.close() }
})
