const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const { PUBLIC_ACTIONS, createActionHandlers } = require('../cloudfunctions/catledger-import/src/action-registry')
const contract = require('../shared/catledger-import.json')

test('导入公共契约与事件云函数动作保持一致', function () {
  const names = Object.keys(contract.actions).sort()
  assert.deepEqual([...PUBLIC_ACTIONS].sort(), names)
  const handler = function () {}
  const handlers = createActionHandlers({
    commit: handler, discard: handler, discardFile: handler, get: handler, getFile: handler,
    parse: handler, parseFile: handler, prepare: handler, prepareMany: handler,
    financeUpdateAbandon: handler, financeUpdateCreate: handler, financeUpdateGet: handler,
    financeUpdatePrepare: handler,
    financeUpdateOrganize: handler, financeUpdatePost: handler, financeUpdateUndo: handler,
    financeUpdateUndoImpact: handler, economicEventCorrect: handler,
    economicEventCorrectionImpact: handler, economicEventEvidence: handler, reviewIssueGet: handler,
    reviewIssueList: handler, reviewIssueResolve: handler, reviewIssueResolveAccountMappings: handler,
    reviewIssueReviseAccountMapping: handler
  })
  assert.deepEqual(Object.keys(handlers).sort(), names)
  assert.equal(Object.values(handlers).every(function (value) { return typeof value === 'function' }), true)
})

test('统一 FinanceUpdate 上线后不再公开旧单文件写链路', function () {
  const retired = [
    'imports.prepare', 'imports.parse', 'imports.get', 'imports.commit', 'imports.discard',
    'financeUpdates.create',
    'reviewIssues.reviseAccountMapping'
  ]
  retired.forEach(function (action) {
    assert.equal(contract.actions[action], undefined, action)
    assert.equal(PUBLIC_ACTIONS.includes(action), false, action)
  })
})

test('小程序导入调用只使用已登记动作且底栏进入独立工作台', function () {
  const page = fs.readFileSync(path.join(__dirname, '../miniprogram/pages/import-workbench/index.js'), 'utf8')
  const actions = [...page.matchAll(/callImport\(\s*['"]([^'"]+)['"]/g)].map(function (match) { return match[1] })
  assert.ok(actions.length > 0)
  actions.forEach(function (action) { assert.ok(contract.actions[action], action) })
  const tab = fs.readFileSync(path.join(__dirname, '../miniprogram/custom-tab-bar/index.js'), 'utf8')
  assert.match(tab, /navigateTo\(\{ url: '\/pages\/import-workbench\/index' \}\)/)
  assert.doesNotMatch(tab, /chooseMessageFile/)
})

test('旧版云函数动作错误显示为版本过旧而不是尚未开放', function () {
  const page = fs.readFileSync(path.join(__dirname, '../miniprogram/pages/import-workbench/index.js'), 'utf8')
  const serverErrors = fs.readFileSync(path.join(__dirname, '../cloudfunctions/catledger-import/src/errors.js'), 'utf8')
  assert.match(page, /UNSUPPORTED_ACTION:\s*'导入服务版本过旧，请更新云函数后重试'/)
  assert.match(page, /ERROR_MESSAGES\[error && error\.code\]/)
  assert.match(serverErrors, /UNSUPPORTED_ACTION:\s*'导入服务版本过旧，请更新后重试'/)
  assert.doesNotMatch(page + serverErrors, /当前导入操作尚未开放/)
})

test('导入工作台沿用按需登录与主题组件', function () {
  const config = require('../miniprogram/pages/import-workbench/index.json')
  const source = fs.readFileSync(path.join(__dirname, '../miniprogram/pages/import-workbench/index.js'), 'utf8')
  const markup = fs.readFileSync(path.join(__dirname, '../miniprogram/pages/import-workbench/index.wxml'), 'utf8')
  assert.equal(config.usingComponents['login-sheet'], '/components/login-sheet/index')
  assert.match(source, /loginGuard\.run/)
  assert.match(source, /loginGuard\.run\(this, this\.openFilePicker\.bind\(this\)\)/)
  assert.match(source, /themeService\.bindPage/)
  assert.match(markup, /id="page-login-sheet"/)
})

test('导入工作台以多文件 FinanceUpdate 和 ReviewIssue 取代逐行 post/skip', function () {
  const source = fs.readFileSync(path.join(__dirname, '../miniprogram/pages/import-workbench/index.js'), 'utf8')
  const modelSource = fs.readFileSync(path.join(__dirname, '../miniprogram/pages/import-workbench/model.js'), 'utf8')
  const markup = fs.readFileSync(path.join(__dirname, '../miniprogram/pages/import-workbench/index.wxml'), 'utf8')
  const styles = fs.readFileSync(path.join(__dirname, '../miniprogram/pages/import-workbench/index.wxss'), 'utf8')
  const repository = fs.readFileSync(path.join(__dirname, '../cloudfunctions/catledger-import/src/import-repository.js'), 'utf8')
  assert.match(source, /const MAX_FILES = 5/)
  assert.match(source, /maxFiles: MAX_FILES/)
  assert.match(source, /const remaining = MAX_FILES - this\.data\.files\.length/)
  assert.match(source, /chooseMessageFile\(\{[\s\S]*count: remaining/)
  assert.match(source, /self\.data\.files\.concat\(files\)/)
  assert.match(source, /sameFileContent/)
  assert.match(source, /phase: this\.data\.files\.length \? 'files_ready' : 'idle'/)
  assert.match(source, /callImport\('imports\.prepareMany'/)
  assert.match(source, /callImport\('imports\.parseFile'/)
  assert.match(source, /const FILE_PIPELINE_CONCURRENCY = MAX_FILES/)
  assert.match(source, /model\.runWithConcurrency\([\s\S]*preparedFiles,[\s\S]*FILE_PIPELINE_CONCURRENCY/)
  assert.match(source, /state: 'failed', stateText: '上传失败'/)
  assert.match(source, /phase: 'uploading', busy: true, errorMessage: ''/)
  assert.match(markup, /请重试失败文件或继续添加/)
  assert.match(source, /callImport\('financeUpdates\.prepare'/)
  assert.match(source, /callImport\('financeUpdates\.organize'/)
  assert.match(source, /callImport\('reviewIssues\.get'/)
  assert.match(source, /callImport\('reviewIssues\.resolve'/)
  assert.match(source, /callImport\('economicEvents\.evidence'/)
  assert.match(source, /callImport\('reviewIssues\.resolveAccountMappings'/)
  assert.match(source, /callImport\('financeUpdates\.post'/)
  assert.match(source, /callImport\('financeUpdates\.abandon'/)
  assert.match(markup, /class="review-status-tabs"/)
  assert.match(source, /switchReviewStatus/)
  assert.doesNotMatch(source, /imports\.commit|disposition|canPost/)
  assert.match(source, /label: '解析'/)
  assert.match(source, /label: '账户'/)
  assert.match(source, /label: '整理'/)
  assert.match(source, /label: '入账'/)
  assert.match(markup, /先选择账单/)
  assert.match(markup, /账户归属/)
  assert.match(markup, /整理问题/)
  assert.match(markup, /确认整批入账/)
  assert.match(markup, /其中一份失败不会影响其他文件/)
  assert.match(markup, /上限 5 份 · 单份 5 MB/)
  assert.match(markup, /添加后可开始/)
  assert.match(markup, />添加账单<\/button>/)
  assert.doesNotMatch(markup, />重新选择(?:文件|账单)?<\/button>/)
  assert.match(markup, /class="file-picker-actions"/)
  assert.equal((markup.match(/class="file-picker-action"/g) || []).length, 2)
  assert.match(markup, /class="primary-button stage-primary parse-button \{\{phase === 'uploading' \? 'parse-button-loading' : ''\}\}"/)
  assert.match(markup, /phase === 'uploading' \? '解析中' : '开始解析'/)
  assert.match(markup, /最多 5 份并行处理/)
  assert.match(markup, /正在并行解析，请稍候/)
  assert.match(markup, /class="parse-button-spinner"/)
  assert.match(markup, /原始交易 \{\{item\.evidenceCount\}\} ›/)
  assert.doesNotMatch(markup, /交易摘要|查看 \{\{item\.evidenceCount\}\} 条原始记录/)
  assert.match(markup, /class="funds-route-picker"/)
  assert.match(markup, /!\(currentIssue\.issueType === 'transfer_accounts' && currentIssue\.fundsRoute\)/)
  assert.match(markup, /<view wx:if="\{\{phase === 'idle' \|\| phase === 'selected' \|\| phase === 'uploading' \|\| phase === 'files_ready' \|\| phase === 'organizing'\}\}" class="idle-stage">/)
  assert.match(markup, /class="file-row-side"/)
  assert.match(markup, /class="file-progress \{\{item\.state === 'preparing'/)
  assert.match(styles, /\.file-row-side \{[^}]*flex: 0 0 136rpx;/)
  assert.match(styles, /\.file-progress-idle \.file-progress-value \{ width: 0 !important; \}/)
  assert.match(styles, /\.account-decision-row \{[^}]*min-height: 80rpx;/)
  assert.match(styles, /\.account-compact-name \{[^}]*height: 80rpx;[^}]*line-height: 80rpx;/)
  assert.match(styles, /\.choose-button-secondary\[disabled\] \{[^}]*background-color: var\(--theme-accent-soft, #f5ddcb\) !important;/)
  assert.match(styles, /\.stage-primary\[disabled\],[\s\S]*?\.final-primary\[disabled\] \{[^}]*background-color: var\(--theme-accent-soft, #f5ddcb\) !important;/)
  assert.match(markup, /phase === 'idle' \|\| phase === 'selected' \|\| phase === 'uploading' \|\| phase === 'files_ready' \|\| phase === 'organizing'/)
  assert.doesNotMatch(markup, /phase === 'uploading' \|\| phase === 'organizing' \|\| phase === 'loading'/)
  assert.match(styles, /\.parse-button-spinner \{[^}]*animation: processing-spin 760ms linear infinite;/)
  assert.match(markup, /phase === 'files_ready' \|\| phase === 'organizing'/)
  assert.match(markup, /phase === 'organizing' \? '正在准备账户' : '下一步：确认账户'/)
  assert.doesNotMatch(markup, /正在整理解析结果/)
  assert.match(markup, /disabled="\{\{busy \|\| uploadSummary\.queued === 0 \|\| files\.length > maxFiles\}\}"/)
  assert.match(markup, /其他文件可重试或删除，不会混入本次整理/)
  assert.doesNotMatch(source + markup, /activeUpdateId|active_update|resumeExistingUpdate|继续原来的进度|>继续</)
  assert.match(repository, /actionType: 'replace_unposted_update'/)
  assert.match(repository, /status = 'abandoned'/)
  assert.match(repository, /duplicateDisposition: replacedUpdateId \? 'replaced_unposted_update' : 'reused_unposted'/)
  assert.match(source, /!result\.batch \|\| !result\.batch\.batchId/)
  assert.match(markup, /至少成功解析 1 份账单后才可继续/)
  assert.match(markup, /bindtap="removeFile" aria-role="button">删除<\/view>/)
  assert.match(styles, /\.file-copy \{ width: 0; min-width: 0; overflow: hidden; flex: 1 1 0%; \}/)
  assert.match(styles, /\.file-small-action \{[^}]*width: 64rpx;[^}]*flex: 0 0 64rpx;/)
  assert.match(styles, /\.file-error \{[^}]*display: block;[^}]*width: 100%;[^}]*max-height: 48rpx;/)
  assert.match(styles, /\.file-row-side \{[^}]*width: 136rpx;[^}]*flex: 0 0 136rpx;/)
  assert.ok(markup.indexOf('class="file-batch"') < markup.indexOf('class="file-picker-actions"'))
  assert.doesNotMatch(markup, /以前|之前/)
  assert.match(markup, /本次所有账单都会回滚/)
  assert.match(markup, /放弃本批账单/)
  assert.match(markup, /update && phase === 'review' && currentStep === 1/)
  assert.match(styles, /\.abandon-batch-button\[disabled\] \{[^}]*background-color: transparent !important;/)
  assert.match(markup, /正式账户和账本不会改变/)
  assert.match(markup, /class="sheet-layer"/)
  assert.doesNotMatch(markup, /FINANCE UPDATE|primaryReasonCode|post\/skip/)
  assert.match(markup, /把不同渠道的账单，整理成一本账/)
  assert.match(styles, /\.stage-track/)
  assert.match(styles, /\.file-list/)
  assert.match(styles, /\.file-picker-actions \{ display: flex;/)
  assert.match(styles, /\.account-proof-list/)
  assert.match(markup, /class="account-mode-trigger/)
  assert.match(markup, /bindtap="openAccountChoice"/)
  assert.doesNotMatch(markup, /bindchange="changeAccountChoice"/)
  assert.match(markup, /class="workflow-sheet account-choice-sheet"/)
  assert.match(markup, /仅本次不计入/)
  assert.match(markup, /以后不计入/)
  assert.match(markup, /下次仍重新选择，不会自动跳过/)
  assert.match(markup, /bindinput="bindAccountChoiceSearch"/)
  assert.ok(markup.indexOf('仅本次不计入') < markup.indexOf('class="account-choice-section-title">其他账户'))
  assert.match(styles, /\.account-choice-ignore-grid \{ display: flex;/)
  assert.match(styles, /\.account-choice-scroll \{ height:/)
  assert.doesNotMatch(source, /defaultIgnored \? 'ignore_future'/)
  assert.match(markup, /bindinput="bindAccountDraftName"/)
  assert.match(markup, /bindchange="changeAccountDraftType"/)
  assert.match(markup, /bindtap="completeAccountMapping"/)
  assert.match(source, /model\.suggestExistingAccount\(issue\.accountContext, accounts\)/)
  assert.doesNotMatch(modelSource, /\\p\{/)
  assert.match(modelSource, /typeof normalized\.normalize === 'function'/)
  assert.match(markup, /已根据账户名称、银行和尾号推荐已有账户，请核对/)
  assert.match(markup, /确认整批入账前不会创建或修改正式账户/)
  assert.doesNotMatch(markup, /class="account-issue-label">选择账户归属/)
  assert.match(source, /model\.reviewIssueRows\(issueGroups\.review\)/)
  assert.doesNotMatch(source, /refundChoices/)
  assert.match(markup, /class="review-status-tab \{\{activeReviewStatus/)
  assert.match(markup, /wx:for="\{\{reviewGroups\}\}"/)
  assert.match(source, /label: '待整理'/)
  assert.match(source, /label: '已排除'/)
  assert.match(source, /label: '重复记录'/)
  assert.doesNotMatch(markup, /class="review-subtabs"/)
  assert.doesNotMatch(source, /switchReviewGroup|visibleReviewGroups|activeReviewGroupType/)
  assert.doesNotMatch(markup, /class="review-sequence-card"/)
  assert.doesNotMatch(markup, /逐笔核对退款关系|确认后自动进入下一笔/)
  assert.doesNotMatch(markup, /class="[^"]*refund-issue-row/)
  assert.match(markup, /class="review-decision-card"/)
  assert.doesNotMatch(source, /_continuousIssueType|continuousType/)
  assert.match(markup, /\{\{issue\.label\}\}/)
  assert.match(markup, /\{\{preview\.amountText\}\}/)
  assert.match(markup, /只显示有证据支持的候选/)
  assert.match(markup, /请选择这笔退款对应的原消费|确认退款关系/)
  assert.match(markup, /本批没有匹配到原消费/)
  assert.match(markup, /bindtap="markRefundPending"/)
  assert.match(source, /resolveIssue\('mark_refund_pending'/)
  assert.doesNotMatch(markup, /涉及 \{\{item\.memberCount\}\} 个关联对象/)
  assert.doesNotMatch(markup, /\{\{item\.amountMinor\}\} \{\{item\.currency\}\}/)
  assert.match(styles, /\.review-decision-card/)
  assert.match(styles, /\.relation-selected \{ background: var\(--theme-accent-soft/)
  assert.match(markup, />转入账户<\/text>/)
  assert.doesNotMatch(markup, />对方账户<\/text>/)
  assert.match(markup, /class="sheet-utility-actions"/)
  assert.ok(markup.indexOf('sheet-utility-actions') < markup.indexOf('保存选择'))
  assert.match(styles, /\.event-list \{[^}]*background: var\(--theme-accent-soft/)
  assert.match(styles, /\.sheet-secondary \{[^}]*background: var\(--theme-accent-soft/)
  assert.match(styles, /\.final-summary/)
})
