const test = require('node:test')
const assert = require('node:assert/strict')
const { fixture, runtime, flush } = require('./helpers/paged-workbench')
const tap = dataset => ({ currentTarget: { dataset } })
const installment = { creditStatement: true, factKind: 'billing', component: 'principal', periodNumber: 3, totalTerms: 6, originKind: 'cash_borrowing' }

test('本金出账列表和原文说明期次，不提供实际还款编辑入口', async t => {
  const data = fixture(1)
  Object.assign(data.events[0], { economicNature: 'repayment', flowDirection: 'neutral', installment })
  const { page } = runtime(data)
  t.after(() => page.onUnload())
  page.data.activeReviewStatus = 'completed'
  await page.setStep({ currentStep: 3 })
  const row = page.data.reviewedEvents[0]
  assert.equal(row.natureLabel, '分期本金出账')
  assert.match(row.displayDetailMeta, /第3期／共6期/)
  await page.openReviewDetails(tap({ id: row.eventId }))
  assert.match(page.data.reviewDetailSheet.installmentNote, /关联或新建分期计划/)
  assert.equal(page.data.reviewDetailSheet.repaymentEditable, false)
  assert.equal(page.data.reviewDetailSheet.reviewEditable, false)
  page.closeReviewDetails()
  await page.openEvidence(tap({ id: row.eventId }))
  assert.equal(page.data.evidenceSheet.repaymentEditable, false)
  assert.match(page.data.evidenceSheet.installmentNote, /不记实际还款/)
  assert.match(page.data.evidenceSheet.installmentNote, /关联或新建分期计划/)
})

test('人工转账与分期出账冲突时需明确选择本金出账，保留账户并清除原对端', async t => {
  const data = fixture(1, true)
  Object.assign(data.events[0], { economicNature: 'internal_transfer', flowDirection: 'neutral', installment,
    counterpartyLedgerAccountId: 'synthetic-target' })
  Object.assign(data.issues[0], { issueType: 'field_conflict', primaryReasonCode: 'core_fields_conflict', subject: data.events[0] })
  const { page } = runtime(data)
  t.after(() => page.onUnload())
  await flush()
  await page.openIssue(tap({ id: 'synthetic-issue' }))
  assert.equal(page.data.currentIssue.installmentPrincipal, true)
  assert.match(page.data.currentIssue.decisionText, /本期分期本金出账/)
  assert.equal(page.data.currentIssue.missingAccountLabel, '所属信用卡')
  const index = page.data.natureOptions.findIndex(option => option.value === 'repayment')
  assert.equal(page.data.natureOptions[index].label, '分期本金出账')
  assert.equal(page.refreshIssueFieldsDraft().valid, false)
  page.changeIssueNature({ detail: { value: index } })
  const draft = page.refreshIssueFieldsDraft()
  assert.equal(draft.valid, true)
  assert.equal(draft.fields.economicNature, 'repayment')
  assert.equal(draft.fields.flowDirection, 'neutral')
  assert.equal(draft.fields.counterpartyLedgerAccountId, null)
  assert.equal(draft.fields.categoryId, null)
})
