import { readFileSync } from 'node:fs';

import { describe, expect, it } from 'vitest';

function source(path: string): string {
    return readFileSync(new URL(path, import.meta.url), 'utf8');
}

describe('personal-finance simple web workflow', () => {
    it('keeps one top-level overview and one unified add entry', () => {
        const layout = source('../../../components/desktop/MainPageLayout.vue');

        expect(layout.match(/<router-link to="\/">/g)).toHaveLength(1);
        expect(layout).not.toContain('to="/personal-finance/bills"');
        expect(layout).not.toContain('to="/personal-finance/imports"');
        expect(layout).not.toContain('to="/personal-finance/reconciliation"');
        expect(layout).toContain("tt('Record Transaction')");
        expect(layout).toContain("tt('Import Bill')");
        expect(layout.match(/class="add-transaction-button/g)).toHaveLength(1);
        expect(layout).toContain("router.push('/personal-finance/bills')");
        expect(layout.indexOf("tt('Record Transaction')")).toBeLessThan(layout.indexOf("tt('Import Bill')"));
        expect(layout.indexOf('to="/category/list"')).toBeLessThan(layout.indexOf("tt('Record Transaction')"));

        const personalFinanceLayout = source('../../../components/desktop/PersonalFinancePageLayout.vue');
        expect(personalFinanceLayout).not.toContain('to="/personal-finance/bills"');
        expect(personalFinanceLayout).toContain('to="/account/list"');
        expect(personalFinanceLayout).toContain('to="/personal-finance/loans"');

        const transactionList = source('../../../views/desktop/transactions/ListPage.vue');
        expect(transactionList).toContain('<main-page-layout :no-navbar="true">');
        expect(transactionList).toContain("tt('Transaction Details')");
        expect(transactionList).toContain('class="transaction-period-summary');
        expect(transactionList).toContain('class="transaction-date-range-filter"');
        expect(transactionList).toContain(':items="recentDateRangeOptions"');
        expect(transactionList).toContain('class="transaction-toolbar-actions');
        expect(transactionList).toContain('class="transaction-page-size-control');
        expect(transactionList).toContain('class="transaction-empty-state');
        expect(transactionList).toContain('table-layout: fixed;');
        expect(transactionList).not.toContain('TransactionListPageType.Calendar.type');
        expect(transactionList).not.toContain('<transaction-calendar');
        expect(transactionList).not.toContain("tt('Transaction List')");
        expect(transactionList).not.toContain("tt('Transaction Calendar')");
        expect(transactionList).not.toContain('transaction-gallery-container');
        expect(transactionList).not.toContain('TransactionListPageType.values()');
        expect(transactionList).not.toContain("./import/ImportDialog.vue");
        expect(transactionList).not.toContain("tt('Import')");

        const accountList = source('../../../views/desktop/accounts/ListPage.vue');
        expect(accountList).toContain('to="/personal-finance/loans"');
        expect(layout).toContain("route.path === '/personal-finance/loans'");

        const router = source('../../../router/desktop.ts');
        const userSettingsLayout = source('../../../views/desktop/user/UserSettingsPageLayout.vue');
        expect(router).toContain("path: '/category'");
        expect(router).toContain('component: CategoryPageLayout');
        expect(userSettingsLayout).not.toContain('to="/category/list"');
        expect(userSettingsLayout).not.toContain('to="/tag/list"');
        expect(userSettingsLayout).not.toContain("tt('Advanced Management')");

        const appSettings = source('../../../views/desktop/app/AppBasicSettingPage.vue');
        const mobileSettings = source('../../../views/mobile/SettingsPage.vue');
        const mobileHome = source('../../../views/mobile/HomePage.vue');
        const mobileRouter = source('../../../router/mobile.ts');
        expect(router).not.toContain("path: '/insights/explorer'");
        expect(router).not.toContain("path: '/tag/list'");
        expect(router).not.toContain("path: '/template/list'");
        expect(router).not.toContain("path: '/schedule/list'");
        expect(appSettings).not.toContain("tt('Insights Explorer Page')");
        expect(appSettings).not.toContain("tt('Automatically Add Geolocation')");
        expect(appSettings).toContain("tt('AI Clipboard Text Recognition')");
        expect(appSettings).toContain("tt('AI Image Recognition')");
        expect(mobileSettings).toContain("tt('AI Recognition Settings')");
        expect(mobileHome).toContain("tt('AI Clipboard Text Recognition')");
        expect(mobileHome).toContain("tt('AI Image Recognition')");
        expect(mobileHome).not.toContain('allTransactionTemplates');
        expect(mobileHome).not.toContain('recognizedResponse.tagIds');
        expect(mobileRouter).not.toContain("path: '/tag/list'");
        expect(mobileRouter).not.toContain("path: '/template/list'");
        expect(mobileRouter).not.toContain("path: '/schedule/list'");

        const services = source('../../../lib/services.ts');
        const desktopEditor = source('../../../views/desktop/transactions/list/dialogs/EditDialog.vue');
        const mobileEditor = source('../../../views/mobile/transactions/EditPage.vue');
        expect(services).not.toContain('v1/transaction/templates/');
        expect(desktopEditor).not.toContain('TransactionTemplate');
        expect(desktopEditor).not.toContain('TransactionEditPageType.Template');
        expect(mobileEditor).not.toContain('TransactionTemplate');
        expect(mobileEditor).not.toContain("'/template/add'");
        expect(mobileEditor).not.toContain("'/template/edit'");
    });

    it('keeps review and raw statement records in one route-local workspace', () => {
        const organizer = source('./BillOrganizerPage.vue');
        const router = source('../../../router/desktop.ts');

        expect(organizer).toContain('ResultsFlowPage.vue');
        expect(organizer).not.toContain('TaskWorkbenchPage.vue');
        expect(organizer).toContain('ImportWorkbenchPage.vue');
        expect(organizer).not.toContain('ReconciliationWorkbenchPage.vue');
        expect(organizer).not.toContain('useRoute');
        expect(organizer).not.toContain('useRouter');
        expect(organizer).toContain("ref<BillOrganizerView>('review')");
        expect(organizer).toContain('value="review"');
        expect(organizer).toContain('value="records"');
        expect(organizer).not.toContain('@open-records');
        const results = source('../organizer/desktop/ResultsFlowPage.vue');
        expect(results).toContain('activeWorkflowStep === 1');
        expect(results).toContain('<import-upload-button');
        expect(results).toContain('v-for="batch in selectedBatches"');
        expect(results).toContain('@click="removeBatch(batch.id)"');
        expect(results).not.toContain('v-checkbox-btn');
        expect(results).toContain('organizerApi.getUpdate(selected.id)');
        expect(results).not.toContain("emit('open-records')");
        expect(router).toContain("path: '/personal-finance/bills'");
        expect(router).not.toContain("path: '/personal-finance/imports'");
        expect(router).not.toContain("path: '/personal-finance/reconciliation'");
        expect(router).not.toContain("path: '/personal-finance/dashboard'");
        expect(router).not.toContain("view: 'imports'");
        expect(router).not.toContain("view: 'reconciliation'");
    });

    it('keeps one primary round action while allowing more statements to be added', () => {
        const results = source('../organizer/desktop/ResultsFlowPage.vue');
        const organizer = source('./BillOrganizerPage.vue');
        const upload = source('../components/ImportUploadButton.vue');
        const paymentAccounts = source('../components/PaymentAccountSetupDialog.vue');

        expect(results).toContain('class="source-add"');
        expect(results).toContain('personalFinance.organizerV2.start.add');
        expect(results).toContain('<div class="source-picker">');
        expect(results).not.toContain('<div class="source-picker" v-if="selectedBatches.length">');
        expect(results).not.toContain('<import-upload-button size="large"');
        expect(results).toContain('<div class="actions" v-if="selectedBatchIds.length">');
        expect(results).toContain('@click="startOrganizing"');
        expect(results).toContain('selectedBatchIds.value = readyBatches.value.map(batch => batch.id)');
        expect(results).toContain('paymentAccountSetupDialog.value?.open(selectedBatchIds.value)');
        expect(results).toContain('<payment-account-setup-dialog ref="paymentAccountSetupDialog" @saved="createAndOrganize" />');
        expect(upload).not.toContain('PaymentAccountSetupDialog');
        expect(upload).not.toContain('paymentAccountSetupDialog.value?.open');
        expect(upload).not.toContain('showDuplicateDialog');
        expect(upload).not.toContain('openLatestDuplicate');
        expect(upload).toContain("result.duplicate ? 'duplicate_upload_reparse' : 'initial_upload'");
        expect(paymentAccounts).toContain('Promise.all(batchIds.map');
        expect(paymentAccounts).toContain('const merged = new Map<string, PaymentAccountMember[]>()');
        expect(paymentAccounts).toContain('paymentAccountKey(group)');
        expect(paymentAccounts).toContain('personalFinanceStore.excludePaymentAccount');
        expect(paymentAccounts).toContain('personalFinanceStore.skipPaymentAccount');
        expect(paymentAccounts).toContain('personalFinanceStore.restorePaymentAccount');
        expect(paymentAccounts).toContain('personalFinance.paymentAccount.ignoreCurrent');
        expect(paymentAccounts).toContain('personalFinance.paymentAccount.ignoreFuture');
        expect(paymentAccounts).toContain('personalFinance.paymentAccount.ignoredAccounts');
        expect(paymentAccounts).toContain('if (draft.ignoreMode === \'persistent\')');
        expect(paymentAccounts).not.toContain('if (member.group.excluded) continue;');
        expect(results).toContain('personalFinance.organizerV2.action.continueReview');
        expect(results).toContain('personalFinance.organizerV2.action.confirmAndPost');
        expect(results).toContain('canAbandonUpdate(update)');
        expect(results).toContain('organizerApi.abandon(current');
        expect(results).toContain('abandonAndReselect');
        expect(results.match(/personalFinance\.organizerV2\.action\.abandonAndReselect/g)).toHaveLength(1);
        expect(results).toContain('<import-upload-button v-else-if="update.status === \'posted\' || update.status === \'undone\'" @changed="onImportChanged" />');
        expect(results).toContain("update.value?.status === 'posted' || update.value?.status === 'undone'");
        expect(results).toContain('resetToSourceSelection([batchId])');
        expect(results).not.toContain('personalFinance.organizerV2.action.new');
        expect(results).not.toContain('source-chips');
        expect(results).not.toContain('updateSourceNames');
        expect(results).not.toContain('<header><div><h3>{{ tt(\'personalFinance.organizerV2.sources.title\') }}</h3><p>{{ tt(\'personalFinance.organizerV2.sources.lockedHint\') }}</p></div><import-upload-button');
        expect(results).not.toContain('<v-menu>');
        expect(results).not.toContain('personalFinance.organizerV2.sources.continue');
        expect(results).not.toContain('mdiDotsHorizontal');
        expect(results).toContain('visibilitychange');
        expect(results).not.toContain('organizeCurrent');
        expect(results).not.toContain('mdiRefresh');
        expect(results).not.toContain('@click="load"');
        expect(results).toContain('<footer v-if="activeWorkflowStep === 2">');
        expect(results).toContain('eventFilterCount(filter)');
        expect(results).toContain('class="conservation-inline"');
        expect(results).not.toContain('class="round-meta"');
        expect(results).not.toContain('#{{ update.id }}');
        expect(organizer).toContain('class="organizer-sync"');
        expect(organizer).toContain('@sync-label="organizerSyncLabel = $event"');
        expect(results).not.toContain('personalFinance.organizerV2.workflow.title');
        expect(results).not.toContain('personalFinance.organizerV2.workflow.hint');
        expect(results).not.toContain('class="verification"');
        expect(results.match(/class="round-primary-action"/g)).toHaveLength(2);
        expect(results).toContain('<footer v-if="update.needsActionEventCount > 0">');
        expect(results).toContain('class="post-all-action"');
        expect(results).toContain(':disabled="!canPostUpdate(update)"');
        expect(results).toContain('personalFinance.organizerV2.action.resolveBeforePost');
        expect(results).not.toContain('activeWorkflowStep !== 2');
        expect(results).not.toContain('personalFinance.organizerV2.events.eyebrow');
        expect(results).not.toContain('personalFinance.organizerV2.events.hint');
        expect(results).toContain('class="issue-actions"');
        expect(results).toContain('v-if="reviewIssueCount(issue) > 1"');
        expect(results).toContain('reviewIssueActionLabel(issue)');
        expect(results).toContain('personalFinance.organizerV2.issue.action.confirmRelationship');
        expect(results).toContain('v-model="selectedSameEventDecision"');
        expect(results).toContain('value="confirm_same"');
        expect(results).toContain('value="confirm_distinct"');
        expect(results).not.toContain('@click="confirmSame(issue)"');
        expect(results).not.toContain('@click="confirmDistinct(issue)"');
        expect(results).toContain('class="account-route"');
        expect(results).toContain('movementSourceName(event)');
        expect(results).toContain('movementDestinationName(event)');
        expect(results).not.toContain('@click="excludeIssue(issue)"');
        expect(results).not.toContain('personalFinance.organizerV2.issue.excludeOne');
        expect(results).not.toContain('personalFinance.organizerV2.events.statementClues');
        expect(results).not.toContain('reviewIssueTitle');
        expect(results).not.toContain('排除本问题中的记录');
        expect(results).not.toContain('.issue-card > footer');
        expect(results).toContain('personalFinance.organizerV2.audit.compactSummary');
        expect(results).toContain('<footer v-if="activeWorkflowStep === 2">');
        expect(results).not.toContain('<footer v-if="activeWorkflowStep !== 1">');
        expect(results).toContain('excluded: update.excludedEventCount');
        expect(results).toContain('anomaly: excludedAnomalyCount');
        expect(results).toContain('excludedAnomalyEvents.value.length');
        expect(results).toContain("if (filter === 'audit') return update.value.duplicateEvidenceCount");
        expect(results).toContain('update.postedEventCount');
        expect(results).toContain('item.row.rawFields');
        expect(results).toContain('personalFinance.organizerV2.evidence.originalFields');
        expect(results).toContain('personalFinance.organizerV2.audit.title');
        expect(results).toContain('--record-row-min-height: 58px');
        expect(results).toContain('min-height: var(--record-row-min-height)');
        expect(results).toContain('font-size: var(--record-title-size)');
        expect(results).toContain("['needs_action', 'excluded', 'audit']");
        expect(results).not.toContain("['needs_action', 'uncategorized', 'excluded', 'audit']");
        expect(results).toContain('showOnlyUncategorized');
        expect(results).toContain('personalFinance.organizerV2.category.pendingCount');
        expect(results).toContain('personalFinance.organizerV2.category.showOnlyPending');
        expect(results).toContain('personalFinance.organizerV2.events.reviewComplete');
        expect(results).toContain('class="category-toolbar"');
        expect(results).not.toContain('class="workbench-actions"');
        expect(results).toContain('v-for="event in visibleEvents"');
        expect(results).toContain("events.value.filter(event => isCategorisable(event) && !event.categoryId)");
        expect(results).toContain("eventFilter === 'ready' && isCategorisable(event) && update.status === 'review'");
        expect(results).toContain("personalFinance.organizerV2.category.notRequired");
        expect(results).toContain('class="context event-account"');
        expect(results).toContain('class="category-field"');
        expect(results).toContain('class="category-edit-action"');
        expect(results).not.toContain('event-account-category');
        expect(results).not.toContain('inline-category');
        expect(results).not.toContain("eventFilter.value === 'uncategorized'");
        expect(results).toContain("function isCategorisable(event: EconomicEvent): boolean { return ['expense', 'income', 'fee'].includes(event.economicNature); }");
        expect(results).toContain(':class="event.economicNature"');
        expect(results).toContain('.event-row .event-copy > span.income { color: rgb(var(--v-theme-success)); }');
        expect(results).toContain("function workflowStepForFilter(filter: ResultsFilter): 2 | 3 { return filter === 'ready' || filter === 'posted' ? 3 : 2; }");
        expect(results).toContain('activeWorkflowStep.value = workflowStepForFilter(eventFilter.value)');
        expect(results).not.toContain("filter === 'posted' || filter === 'uncategorized' ? 3 : 2");
        expect(results).not.toContain("['needs_action', 'anomaly', 'excluded', 'audit']");
        expect(results).toContain('class="event-kind"');
        expect(results).toContain('grid-template-columns: 5rem 44px');
        expect(results).toContain("v-if=\"eventFilter === 'excluded'\"");
        expect(results).toContain("v-if=\"eventFilter !== 'excluded'\"");
        expect(results).not.toContain("eventFilter === 'excluded' ? eventExcludedLabel(event)");
        expect(results).toContain("v-if=\"eventFilter === 'excluded'\">{{ eventExcludedContext(event) }}");
        expect(results).not.toContain("eventFilter === 'anomaly'");
        expect(results).toContain("events.value = await listAllEvents(update.value.id, eventFilter.value)");
        expect(results).toContain('personalFinance.organizerV2.excluded.accountIgnoredHint');
        expect(results).not.toContain("['needs_action', 'ready', 'excluded', 'audit']");
        expect(results).not.toContain("['needs_action', 'ready', 'posted', 'excluded', 'audit']");
        expect(results).not.toContain("'all'");
        expect(results).not.toContain("'relation'");
        expect(results).toContain('showPostingStep');
        expect(results).toContain('postingStepShowsPosted');
        expect(results).toContain('class="posting-complete"');
        expect(results).toContain("eventFilter === 'audit'");
        expect(results).toContain("eventFilter !== 'audit'");
        expect(results).toContain('auditEvents.value = sortEconomicEventsOldestFirst(pages.flat().filter(event => event.evidenceCount > 1))');
        expect(results).toContain('return sortEconomicEventsOldestFirst(result)');
        expect(results).toContain('v-for="issue in sortedReviewIssues"');
        expect(results).toContain('!isDisplayDate(value)');
        expect(results).toContain("reasons.includes('auto_same_event')");
        expect(results).toContain('personalFinance.organizerV2.audit.amountWarning');
        expect(results).toContain('v-for="event in auditEvents"');
        expect(results).not.toContain('showAllAuditEvents');
        expect(results).not.toContain('auditPreviewLimit');
        expect(results).not.toContain('原始证据与来源');
    });

    it('keeps raw records non-posting and reviews ledger fields in the organizer', () => {
        const records = source('./ImportWorkbenchPage.vue');
        const results = source('../organizer/desktop/ResultsFlowPage.vue');

        expect(records).not.toContain('PostingDialog.vue');
        expect(records).not.toContain('openPosting(row)');
        expect(results).toContain('selectedLedgerAccountId');
        expect(results).toContain('selectedCounterpartyLedgerAccountId');
        expect(results).toContain('selectedCounterpartyLedgerAccountId.value !== selectedLedgerAccountId.value');
        expect(results).toContain('selectedCategoryId');
        expect(results).toContain("categoryScope: canBatchCategoryCorrection.value ? selectedCategoryScope.value : 'single'");
        expect(results).toContain('value="matching_uncategorized"');
		expect(results).toContain('matchingCategoryEventCount.value > 1');
		expect(results).toContain('getCategoryCorrectionScope(currentUpdate.id, event.id)');
        expect(results).toContain('let fieldMask = 1 | 4 | 8');
        expect(results).toContain('fieldMask |= 128');
        expect(results).not.toContain('fieldMask |= 256');
        const locale = source('../../../locales/zh_Hans.json');
        expect(locale).toContain('"title": "核对资金账户"');
        expect(locale).toContain('"audit": "重复记录"');
        expect(locale).not.toContain('"filter": { "needs_action": "必须处理", "anomaly": "交易异常"');
        expect(locale).toContain('"filter": { "needs_action": "待确认"');
        expect(locale).toContain('"resolveBeforePost": "还有 {count} 项待确认"');
        expect(locale).not.toContain('"resolveBeforePost": "请先处理 {count} 个问题"');
        expect(locale).toContain('"optionalHint": "不影响入账，但会影响分类图表"');
		expect(locale).toContain('"scopeChecking": "正在核对本轮同类交易…"');
		expect(locale).toContain('"scopeMatching": "应用到本轮同类交易（共 {count} 笔）"');
        expect(locale).toContain('"reviewComplete": "待确认项已全部处理，可以进入「可入账」整批入账。"');
        expect(locale).toContain('"accountIgnored": "账户已忽略"');
        expect(locale).toContain('"accountIgnoredHint": "该资金账户已设为忽略，无需补账户或分类"');
        expect(locale).toContain('"compactSummary": "{evidence} 条原始记录 − {duplicates} 条重复记录 − {excluded} 条不入账记录（含 {anomaly} 笔交易异常）');
    });

    it('teaches the batch-first workflow and progressively discloses loan details', () => {
        const dashboard = source('../dashboard/desktop/DashboardPage.vue');
        const loans = source('../loans/desktop/LoanWorkbenchPage.vue');

        expect(dashboard).toContain('personalFinance.dashboard.gettingStarted.boundary');
        expect(dashboard).toContain('to="/personal-finance/bills"');
        expect(dashboard).not.toContain('/personal-finance/bills?view=imports');
        expect(dashboard).not.toContain('/personal-finance/bills?view=reconciliation');
        expect(loans).toContain('<section class="calculation-summary');
        expect(loans).toContain('<loan-calculation-result-panel');
        expect(loans).not.toContain('personalFinance.loans.advanced.hint');
        expect(loans).toContain('personalFinance.loans.candidates.title');
        expect(loans).toContain('completeInstallmentCandidate(candidate)');
        expect(loans).toContain("route.query['installmentCandidate']");
        expect(loans).toContain('openRequestedInstallmentCandidate()');
        expect(loans).toContain("fundingType: 'purchase_installment'");
        expect(loans).toContain('installmentApi.confirmCandidate');
        const organizer = source('../organizer/desktop/ResultsFlowPage.vue');
        expect(organizer).toContain('value="existing"');
        expect(organizer).toContain('rankCompatibleInstallmentContracts');
        expect(organizer).toContain('loanApi.listContracts');
        expect(organizer).toContain('linkedContractId: contract.contract.id');
        expect(organizer).toContain('value="create"');
        expect(organizer).toContain('<loan-contract-form');
        expect(organizer).toContain('<loan-calculator-panel');
        expect(organizer).toContain("decision: 'confirm_installment_principal'");
        expect(organizer).toContain('installmentCandidateId: candidate.id');
        expect(organizer).not.toContain('value="repayment"');
        expect(organizer).toContain('installmentApi.confirmCandidate');
        const locale = source('../../../locales/zh_Hans.json');
        expect(locale).toContain('"title": "这笔账单分期怎么处理？"');
        expect(locale).toContain('"createTitle": "新建分期记录"');
        expect(locale).toContain('"existing": "关联已有分期记录（{count} 个可选）"');
        expect(locale).toContain('"existingListHint": "当前已选择；展开查看全部 {count} 项"');
        expect(locale).toContain('"create": "新建并关联分期记录"');
        expect(locale).toContain('"draftBoundary": "这里填写的是本轮草稿。只有整批入账成功后才会创建正式分期记录；放弃本轮不会保留。"');
        expect(locale).toContain('"createConfirm": "保存并继续整理"');
        expect(locale).not.toContain('"repayment": "这次确实有钱转出去还款"');
    });
});
