blank_issues_enabled: false
contact_links:
  - name: Usage Questions
    url: https://github.com/gaohongxiang/catledger/discussions/categories/q-a
    about: Questions about using CatLedger can be discussed in GitHub Discussions.
